### ISSUE TITLE
source_url on supermarket is not up-to-date

### ISSUE THREAD

**Issue by kamaradclimber** [windowschefcookbooks/seven_zip#1]
See on https://supermarket.chef.io/cookbooks/seven_zip

the source_url is not pointing to this repo (and points to the deprecated one).

Could you fix it?

thanks

**Comment by kamaradclimber** [comment]
This impacts us because we use source_url to generate changelog on all cookbooks that we could upgrade.
Tag 2.0.1 does not exist on the old repo which makes this process crash.

**Comment by heathsnow** [comment]
Supermarket `source_url` has been [updated](https://supermarket.chef.io/cookbooks/seven_zip).

**Comment by kamaradclimber** [comment]
Great thanks you!
