### ISSUE TITLE
Checksum does not appear to work

### ISSUE THREAD

**Issue by LuneraSteve** [windowschefcookbooks/seven_zip#12]
When running the following block:

```
seven_zip_archive "test" do
  path 'c:\\'
  checksum '<some checksum>'
  source '<local or http path>'
end
```
My expectation is that if `checksum` matches; that the zip file will NOT be extracted.  However, no matter what I put in for a checksum, the zip file is always extracted.

Any suggestions?

**Comment by jugatsu** [comment]
`seven_zip` resource is not idempotent by design.

Just use `File.exist?` to prevent run on each converge:

```ruby
seven_zip_archive 'extract installer' do
  source url
  path Chef::Config['file_cache_path']
  overwrite true
  checksum node['example']['checksum']
  not_if { File.exist?(zip_path.to_s) }
  action :extract
end

```
