### ISSUE TITLE
Deprecation warning windows_package

### ISSUE THREAD

**Issue by coderjoe** [windowschefcookbooks/seven_zip#2]
Deprecation warnings are being outputted when using the seven_zip cookbook:

>  WARN: Please use the package resource available in Chef Client 12.6+.
windows_package will be removed in the next major version release
of the Windows cookbook on 4/2017.

How difficult would it be to migrate to the package resource as suggested in the deprecation message?

**Comment by sneal** [comment]
Fixed by #6

**Comment by sneal** [comment]
Nevermind, it actually wasn't fixed. Well it was in one commit, then reverted.

**Comment by linusruth** [comment]
It is fine to continue using 'windows_package' resource, as it has been removed from the 'windows' cookbook and added to core Chef.  The OP should be able to eliminate the deprecation warnings by upgrading Chef, and installing the latest versions of the 'windows' and 'seven_zip' cookbooks.
