### ISSUE TITLE
The "overwrite" attribute does not honor "false"

### ISSUE THREAD

**Issue by jamesbannan** [windowschefcookbooks/seven_zip#3]
The "overwrite" attribute doesn't seem to be honored when the setting is either not configured (default "false") or when "false" is stated explicitly in the cookbook.

Run a Chef cookbook where the seven_zip_archive method is called.  The file extraction works successfully.  Re-run the cookbook without deleting the extracted content and the method fails, as 7Zip is attempting to prompt whether the files should be overwritten.

Setting the "overwrite" attribute to "true" is honored.

**Comment by sneal** [comment]
Fixed by #5
